#!/bin/bash
if [ "$#" -eq 3 ]; then
  case $2 in
    +) res=$(( $1 + $3 )) ;;
    -) res=$(( $1 - $3 )) ;;
    \*) res=$(( $1 * $3 )) ;;
    /) res=$(( $1 / $3 )) ;;
    *) echo "Invalid operator"; exit 1 ;;
  esac
  echo "Result: $res"
else
  echo "Usage: num1 operator num2"
fi
